server:
  port: 9010

spring:
  application:
    name: epms

  datasource:
    url: jdbc:postgresql://43.205.24.208:5432/epms
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: m.harikascm@gmail.com
    password: eoyfwcxkgzkrnbeu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  encryption:
    simpleEncSecret: 8F3dK9@Q!2zL7X#A
