package com.cdl.epms.common.enums;

public enum GoalStatus {
    NOT_STARTED,
    PREDEFINED_SUBMITTED,
    SUBMITTED_TO_MANAGER,
    MANAGER_REVIEWED,
    SENT_TO_EMPLOYEE,
    ACCEPTED_BY_EMPLOYEE,
    FINAL_SUBMITTED_TO_HR
}